import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Box, Check, CircuitBoard, Cpu, Filter, Menu, Package, Search, X } from "lucide-react";
import { ComponentDocuments } from "@/components/ComponentDocuments";
import { ComponentPreview } from "@/components/ComponentPreview";
import { WorkspaceSidebar } from "@/components/WorkspaceSidebar";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { usePartPreviews } from "@/lib/lab/usePartPreviews";
import { addToBom, readBom, componentCatalog, catalogCategories, type CatalogComponent, type BomEntry } from "@/lib/componentCatalog";

export const Route = createFileRoute("/catalog")({head:()=>({meta:[{title:"Component Catalog | HardwareMate AI"}]}),component:CatalogPage});
function CatalogPage() {
  const navigate=useNavigate(); const previews=usePartPreviews();
  const [menu,setMenu]=useState(false), [query,setQuery]=useState(""), [category,setCategory]=useState("All"), [voltage,setVoltage]=useState("All");
  const [previewKey,setPreviewKey]=useState<string|null>(null);
  const [selected,setSelected]=useState<CatalogComponent|null>(null), [bom,setBom]=useState<BomEntry[]>([]), [notice,setNotice]=useState("");
  useEffect(()=>setBom(readBom()),[]);
  const normalized=query.trim().toLowerCase().normalize("NFKC").replace(/[أإآ]/g,"ا");
  const items=componentCatalog.filter(item=>(category==="All"||item.category===category)&&(voltage==="All"||item.voltage===Number(voltage))&&`${item.name} ${item.arabic} ${item.key} ${item.model}`.toLowerCase().normalize("NFKC").replace(/[أإآ]/g,"ا").includes(normalized));
  const add=(item:CatalogComponent)=>{try{setBom(addToBom(item.key));setNotice(`${item.name} added to BOM`);}catch{setNotice("Could not save BOM in this browser. Please enable local storage.");}};
  const openLab=(item:CatalogComponent)=>navigate({to:"/lab",search:{add:item.model,request:Date.now().toString()}});
  return <div className="dashboard-background catalog-background min-h-screen"><div className="mx-auto flex max-w-[1800px] gap-4 p-3 lg:p-4">
    {menu&&<button onClick={()=>setMenu(false)} aria-label="Close navigation overlay" className="fixed inset-0 z-30 bg-foreground/20 lg:hidden"/>}
    <WorkspaceSidebar active="Component Catalog" open={menu} onClose={()=>setMenu(false)} onSelect={label=>{if(label==="Dashboard")navigate({to:"/"});else if(label==="3D Lab")navigate({to:"/lab"});else if(label!=="Component Catalog")navigate({to:"/project"});}} className="lg:sticky lg:top-4 lg:h-[calc(100vh-32px)]"/>
    <main className="min-w-0 flex-1 space-y-4 pb-6">
      <header className="flex flex-wrap items-center justify-between gap-3 px-1 py-2"><div className="flex items-center gap-3"><button onClick={()=>setMenu(true)} aria-label="Open menu" className="lg:hidden"><Menu/></button><div><p className="text-[11px] text-muted-foreground">Workspace / Components</p><h1 className="mt-1 text-2xl font-bold">Component Catalog</h1></div></div><Button asChild variant="secondary" size="sm"><Link to="/project" search={{action:"bom"}}><Package size={15}/>View BOM · {bom.reduce((sum,item)=>sum+item.quantity,0)}</Link></Button></header>
      <section className="glass-panel catalog-intro rounded-[20px] p-5"><div className="flex items-center gap-3"><span className="project-abstract-icon"><CircuitBoard size={25}/></span><div><p className="project-eyebrow">THE BUILDING BLOCKS OF YOUR NEXT IDEA</p><h2 className="mt-1 text-lg font-bold">Find the right component. Start building.</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">43 approved components · Explore specifications, build your BOM, and assemble in 3D.</p></div></div><div className="relative mt-5"><Search size={18} className="absolute left-3 top-3 text-muted-foreground"/><input aria-label="Search components" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search بالعربي، English، or component key…" className="glass-inset h-11 w-full rounded-xl pl-10 pr-10 text-sm outline-none focus:ring-2 focus:ring-ring/40"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery("")} className="absolute right-3 top-3"><X size={17}/></button>}</div></section>
      <div className="grid gap-4 xl:grid-cols-[190px_1fr]">
        <aside className="glass-panel h-fit rounded-[18px] p-4 xl:sticky xl:top-4"><h2 className="mb-4 flex items-center gap-2 text-xs font-bold"><Filter size={15}/>Filter Components</h2><label className="text-[11px] font-semibold" htmlFor="catalog-category">Category / التصنيف</label><select id="catalog-category" value={category} onChange={e=>setCategory(e.target.value)} className="catalog-select mt-2 h-10 w-full rounded-lg px-2 text-xs"><option value="All">All categories</option>{catalogCategories.map(name=><option key={name} value={name}>{name}</option>)}</select><p className="mb-2 mt-5 text-[11px] font-semibold">Typical supply voltage</p><div className="flex flex-wrap gap-1.5">{["All","3.3","5","12"].map(value=><button key={value} aria-pressed={voltage===value} onClick={()=>setVoltage(value)} className={`catalog-filter rounded-lg px-2.5 py-2 text-xs ${voltage===value?"catalog-filter-active":""}`}>{value==="All"?"All":`${value}V`}</button>)}</div><Button variant="ghost" size="sm" className="mt-4 w-full text-xs" onClick={()=>{setCategory("All");setVoltage("All");setQuery("");}}>Clear Filters</Button><p className="mt-4 border-t border-border/50 pt-3 text-[10px] leading-5 text-muted-foreground">Supply voltage depends on the board variant. Check pin voltage before wiring; supply and logic voltage can differ.</p></aside>
        <div><div className="mb-3 flex items-center justify-between text-xs"><p><strong>{items.length}</strong><span className="text-muted-foreground"> of 43 components</span></p><span className="text-[10px] text-primary">Technical library</span></div>{notice&&<div role="status" className="catalog-notice mb-3 flex items-center justify-between gap-3 rounded-xl p-3 text-xs"><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice("")}><X size={14}/></button></div>}
          <div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-3">{items.map(item=><article key={item.key} className="glass-panel catalog-card flex min-w-0 flex-col rounded-[18px] p-4">{previewKey===item.key&&!selected?<ComponentPreview model={item.model}/>:<button aria-label={`Explore ${item.name} in 3D`} onClick={()=>setPreviewKey(item.key)} className="catalog-image flex h-32 items-center justify-center rounded-xl">{previews[item.model]?<img src={previews[item.model]} alt={item.name} loading="lazy" className="h-28 w-full object-contain"/>:<Cpu size={42} className="text-primary"/>}<span className="catalog-preview-label">Explore 3D ↗</span></button>}<div className="mt-3 flex-1"><span className="catalog-category">{item.category}</span><h2 dir="rtl" className="mt-2 text-left text-sm font-bold leading-6">{item.arabic}</h2><p className="mt-1 text-xs font-semibold leading-5">{item.name}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{item.key}</p><div className="mt-3 flex items-center justify-between text-[10px]"><span className="text-primary">{item.voltage?`${item.voltage}V supply`:"Circuit-dependent"}</span><span className="text-muted-foreground">{item.def.pins.length} pins</span></div></div><div className="catalog-card-footer"><button onClick={()=>setSelected(item)} className="catalog-specifications">View specifications <span aria-hidden="true">→</span></button><div className="grid grid-cols-2 gap-2"><Button size="sm" variant="secondary" className="px-1.5 text-[10px]" onClick={()=>add(item)}>{bom.some(entry=>entry.key===item.key)?<Check size={13}/>:<Package size={13}/>}Add to BOM</Button><Button size="sm" className="px-1.5 text-[10px]" onClick={()=>openLab(item)}><Box size={13}/>Add to 3D Lab</Button></div></div></article>)}</div>
          {!items.length&&<div className="glass-panel rounded-2xl p-10 text-center"><Search className="mx-auto text-primary"/><h2 className="mt-3 text-sm font-bold">No matching components</h2><p className="mt-2 text-xs text-muted-foreground">Try another name or clear the filters.</p><Button className="mt-4" variant="secondary" onClick={()=>{setQuery("");setCategory("All");setVoltage("All");}}>Clear Filters</Button></div>}
        </div>
      </div>
    </main>
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="glass-panel glass-strong catalog-details max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription dir="rtl">{selected?.arabic}</DialogDescription></DialogHeader>{selected&&<><ComponentPreview model={selected.model}/><p dir="rtl" className="text-sm leading-7">{selected.description}</p><div className="glass-inset grid grid-cols-2 gap-3 rounded-xl p-3 text-xs"><div><p className="text-muted-foreground">Typical supply</p><strong>{selected.voltage?`${selected.voltage} V`:"Circuit-dependent"}</strong></div><div><p className="text-muted-foreground">Catalog current estimate</p><strong>{selected.def.draw?`${selected.def.draw} mA`:"Load-dependent"}</strong></div></div><ComponentDocuments componentKey={selected.key}/><section><h3 className="text-xs font-bold">Pins · {selected.def.pins.length}</h3><div className="mt-2 flex flex-wrap gap-1.5">{selected.def.pins.map((pin,i)=><span key={i} title={pin.functions} className="glass-inset rounded-md px-2 py-1 font-mono text-[10px]">{pin.name}{pin.voltage!==undefined?` · ${pin.voltage}V`:""}</span>)}</div></section><section className="catalog-notice rounded-xl p-3"><h3 className="text-xs font-bold">Compatibility notes</h3><p className="mt-2 text-xs leading-6">Connect a common ground and match signal voltage to your controller. Motors and relays need appropriate driver circuitry. Current estimates depend on load and board variant.</p>{["raspberry_pi_4","water_pump_5v"].includes(selected.key)&&<p className="mt-2 text-xs leading-6">The 3D preview uses the existing {selected.def.name} model as a visual reference. Its lab specifications differ from this catalog entry; verify the component variant before wiring.</p>}</section><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>add(selected)}><Package size={15}/>Add to BOM</Button><Button onClick={()=>openLab(selected)}><Box size={15}/>Add to 3D Lab</Button></div></>}</DialogContent></Dialog>
  </div></div>;
}
