import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CircleAlert, Cpu, FileText, FolderKanban, Menu, MessageSquare, Plus, Search, Users, Wallet, Zap } from "lucide-react";
import { WorkspaceSidebar } from "@/components/WorkspaceSidebar";
import { ProjectMedia } from "@/components/ProjectMedia";
import { ProgressRing } from "@/components/ProjectVisuals";
import { WorkshopDashboard } from "@/components/WorkshopDashboard";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { deadlines, project, teammates, useProjectWorkspace } from "@/lib/projectWorkspace";
import { useStudentProfile } from "@/lib/studentProfile";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "HardwareMate | Dashboard" }] }), component: Dashboard });

function Dashboard() {
  const navigate = useNavigate();
  const workspace = useProjectWorkspace();
  const {profile}=useStudentProfile();
  const avatar=profile.photo;
  const [menu, setMenu] = useState(false);
  const [query, setQuery] = useState("");
  const [dialog, setDialog] = useState<string | null>(null);
  const today = teammates[0]!;
  const doneToday = today.tasks.filter((_, i) => workspace.completed.includes(`0-${i}`)).length;
  const openProject = (tab: "overview" | "team" | "components" | "reports" = "overview") => navigate({ to: "/project", search: { tab } });
  const matches = [{ name: `${project.name} — ${project.subtitle}`, tab: "overview" as const }, { name: "Team & today's tasks", tab: "team" as const }, { name: "Components & budget", tab: "components" as const }, { name: "Weekly report & supervisor feedback", tab: "reports" as const }].filter(item => item.name.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="dashboard-background student-dashboard-theme min-h-screen">
    <div className="insight-shell">
      {menu && <button aria-label="Close navigation overlay" onClick={() => setMenu(false)} className="fixed inset-0 z-30 bg-foreground/20 lg:hidden"/>}
      <WorkspaceSidebar active="Dashboard" open={menu} onClose={() => setMenu(false)} onSelect={label => { if(label === "My Project")openProject(); else if(label === "3D Lab")navigate({to:"/lab"}); else if(label === "Component Catalog")navigate({to:"/catalog"}); else if(label === "Reports")openProject("reports"); else if(label === "Team")openProject("team"); else if(label === "Inventory")openProject("components"); else if(label !== "Dashboard")setDialog(label); }} className="lg:sticky lg:top-4 lg:h-[calc(100vh-32px)]"/>
      <main className="insight-main">
        <header className="insight-topbar"><button className="lg:hidden" aria-label="Open menu" onClick={() => setMenu(true)}><Menu/></button><div className="insight-search"><Search size={17}/><input aria-label="Search your workspace" placeholder="Find a project, task or report…" value={query} onChange={e => setQuery(e.target.value)}/>{query.trim() && <div className="insight-search-results">{matches.length ? matches.map(item => <button key={item.name} onClick={() => { setQuery("");openProject(item.tab); }}>{item.name}<ArrowUpRight size={13}/></button>) : <p>No matching items</p>}</div>}</div><button aria-label="Notifications" className="insight-icon-button" onClick={() => setDialog("Notifications")}><Bell size={18}/><span className="insight-notification-dot"/></button><button className="insight-profile" onClick={() => navigate({to:"/profile"})}><img src={avatar} alt=""/><span>{profile.name}<small>Student workspace</small></span></button></header>
        <section className="insight-welcome"><div><p className="insight-eyebrow">YOUR WORKSPACE, AT A GLANCE</p><h1>A little closer<br/><span>to making it work.</span></h1><p>The big picture, your next steps, and what needs a little attention.</p></div><div className="insight-welcome-progress"><ProgressRing value={workspace.progress} size={116} label="Overall project progress"/><div><strong>Project progress</strong><span>{workspace.completedCount} of {workspace.taskCount} tasks complete</span><button onClick={() => openProject()}>Explore project <ArrowUpRight size={13}/></button></div></div></section>
        <section className="insight-metric-strip" aria-label="Workspace overview">
          {[{icon:Zap,label:"Current milestone",value:`${project.milestone} / ${project.milestoneCount}`,note:"Prototype testing",tone:"olive",tab:"overview" as const},{icon:Users,label:"Working together",value:"4",note:"Equal teammates",tone:"blue",tab:"team" as const},{icon:CircleAlert,label:"Open issues",value:String(3+workspace.issues.length),note:"1 needs attention",tone:"orange",tab:"overview" as const},{icon:Wallet,label:"Budget remaining",value:`$${project.budget-project.spent}`,note:`$${project.spent} of $${project.budget} used`,tone:"purple",tab:"components" as const}].map(item => <button key={item.label} onClick={() => openProject(item.tab)} className={`insight-metric tone-${item.tone}`}><span className="insight-color-icon"><item.icon size={19}/></span><div><small>{item.label}</small><strong>{item.value}</strong><p>{item.note}</p></div><ArrowUpRight size={14} className="insight-metric-arrow"/></button>)}
        </section>
        <div className="insight-dashboard-grid">
          <div className="insight-primary-stack">
            <section className="insight-paper insight-project-feature"><div className="insight-project-copy"><p className="insight-eyebrow">ONE PROJECT. A LOT OF POSSIBILITIES.</p><h2>{project.name}<span>{project.subtitle}</span></h2><span className="project-badge"><span className="insight-dot"/>In Progress</span><div className="insight-avatar-stack">{teammates.map((person,i) => i===0 ? <img key={person.name} src={avatar} alt={person.name}/> : <span key={person.name} title={person.name} className={`tone-${person.tone === "rose" ? "orange" : person.tone === "amber" ? "purple" : "blue"}`}>{person.initials}</span>)}<small>Built together</small></div><Button onClick={() => openProject()} size="sm">Open My Project<ArrowRight size={14}/></Button></div><ProjectMedia/></section>
            <section className="insight-paper insight-focus"><div className="insight-section-heading"><div><p className="insight-eyebrow">MAKE TODAY COUNT</p><h2>Your focus today</h2></div><span className="insight-count-pill">{doneToday} / {today.tasks.length}</span></div><div className="insight-focus-list">{today.tasks.map((task,i) => {const done=workspace.completed.includes(`0-${i}`);return <button key={task} onClick={() => workspace.toggleTask(`0-${i}`)} aria-pressed={done}><span className={`insight-task-check ${done?"is-done":""}`}>{done?<Check size={13}/>:<span/>}</span><span className={done?"line-through text-muted-foreground":""}>{task}<small>{i===0?"Design · My assigned task":"Documentation · My assigned task"}</small></span><ArrowUpRight size={14}/></button>})}</div><button className="insight-text-link" onClick={() => openProject("team")}>See the whole team's tasks <ArrowRight size={13}/></button></section>
            <WorkshopDashboard/>
          </div>
          <aside className="insight-secondary-stack">
            <section className="insight-paper"><div className="insight-section-heading"><h2>Coming up</h2><CalendarDays size={18} className="text-muted-foreground"/></div><ol className="insight-deadlines">{deadlines.map(item=><li key={item.name} className={`tone-${item.tone}`}><div className="insight-date"><small>{item.month}</small><strong>{item.day}</strong></div><span className="insight-timeline-dot"/><button onClick={() => openProject(item.type === "Report" ? "reports" : "team")}><strong>{item.name}</strong><span>{item.type} · {item.owner}</span></button></li>)}</ol></section>
            <section className="insight-attention"><div className="insight-color-icon"><FileText size={20}/></div><span className="insight-eyebrow">NEEDS YOUR ATTENTION</span><h2>{workspace.submitted?"Report submitted." : "Your week, ready to share?"}</h2><p>{workspace.submitted?"Your report is marked as submitted for this session." : "The weekly report is due Oct 09. Capture your progress and blockers."}</p><Button size="sm" className="action-blue-solid" onClick={() => openProject("reports")}>{workspace.submitted?"View report":"Prepare report"}<ArrowRight size={14}/></Button></section>
            <section className="insight-paper"><div className="insight-section-heading"><h2>Latest activity</h2><MessageSquare size={17} className="text-muted-foreground"/></div><div className="insight-activity">{[...(workspace.issues.length ? [{name:"New issue recorded",detail:workspace.issues[workspace.issues.length-1]!,icon:CircleAlert,tone:"orange"}] : []),{name:"Supervisor feedback received",detail:"Dr. Lina Hassan · Oct 03",icon:MessageSquare,tone:"blue"},{name:"Circuit updated",detail:"Project design · Latest session",icon:Cpu,tone:"olive"}].map(item=><div key={item.name} className={`tone-${item.tone}`}><span className="insight-color-icon"><item.icon size={15}/></span><p><strong>{item.name}</strong><small>{item.detail}</small></p></div>)}</div></section>
          </aside>
        </div>
        <section className="insight-quick-actions" aria-label="Quick actions"><span>Jump into your workspace</span><button onClick={() => navigate({to:"/lab"})}><FolderKanban size={15}/>3D Lab<ArrowUpRight size={12}/></button><button className="tone-orange" onClick={() => navigate({to:"/project",search:{action:"issue"}})}><Plus size={15}/>Add issue</button><button className="tone-blue" onClick={() => openProject("components")}><Wallet size={15}/>View BOM</button><button className="tone-blue" onClick={() => openProject("reports")}><FileText size={15}/>Weekly report</button></section>
      </main>
    </div>
    <Dialog open={dialog!==null} onOpenChange={open=>!open&&setDialog(null)}><DialogContent className="glass-panel glass-strong"><DialogHeader><DialogTitle>{dialog}</DialogTitle><DialogDescription>Your HardwareMate workspace</DialogDescription></DialogHeader>{dialog==="Notifications"?<div className="space-y-3 text-sm"><p>{workspace.submitted?"Weekly report submitted in this session.":"Weekly report due Oct 09."}</p><p>New feedback from Dr. Lina Hassan.</p><Button onClick={()=>{setDialog(null);openProject("reports");}}>View reports & feedback</Button></div>:dialog==="Your profile"?<div className="flex items-center gap-4"><img src={avatar} alt="NOOR OWASSI" className="size-16 rounded-full"/><div><strong>NOOR OWASSI</strong><p className="text-sm text-muted-foreground">HardwareMate student</p></div></div>:<Button onClick={()=>{setDialog(null);openProject();}}>Open project workspace</Button>}</DialogContent></Dialog>
  </div>;
}
