import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, Bell, BookOpen, Calendar, Camera, Check, CheckCircle2, Github, GraduationCap, Mail, Menu, Pencil, Phone, Plus, Sparkles, StickyNote, Trash2, UserRound, Hash } from "lucide-react";
import { WorkspaceSidebar } from "@/components/WorkspaceSidebar";
import { Button } from "@/components/ui/button";
import { ProgressRing } from "@/components/ProjectVisuals";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { teammates } from "@/lib/projectWorkspace";
import { safeProfileLink, useStudentProfile } from "@/lib/studentProfile";
export const Route=createFileRoute("/profile")({head:()=>({meta:[{title:"My Profile | HardwareMate AI"}]}),component:ProfilePage});
const fields=[{key:"name",label:"Full name",icon:UserRound,type:"text"},{key:"birthYear",label:"Birth year",icon:Calendar,type:"number"},{key:"major",label:"Major",icon:GraduationCap,type:"text"},{key:"studentNumber",label:"Student number",icon:Hash,type:"text"},{key:"year",label:"Academic year",icon:BookOpen,type:"text"},{key:"phone",label:"Phone number",icon:Phone,type:"tel"},{key:"email",label:"Email",icon:Mail,type:"email"}] as const;
function ProfilePage(){
 const navigate=useNavigate(),state=useStudentProfile(),{profile,updateProfile,note,setNote,tasks,setTasks,reminders,setReminders}=state;
 const [menu,setMenu]=useState(false),[editing,setEditing]=useState(false),[draft,setDraft]=useState(profile),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const [taskText,setTaskText]=useState(""),[reminderText,setReminderText]=useState(""),[when,setWhen]=useState("");const photoInput=useRef<HTMLInputElement>(null);
 const completion=Math.round(fields.filter(f=>profile[f.key].trim()).length/fields.length*100),github=safeProfileLink(profile.github);
 const edit=()=>{setDraft({...profile});setError("");setEditing(true);};
 const readPhoto=(file:File|undefined)=>{if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setNotice("Choose a JPG, PNG or WebP photo under 5 MB.");return;}const reader=new FileReader();reader.onload=()=>{const source=String(reader.result),image=new Image();image.onload=()=>{updateProfile({...profile,photo:source});setNotice("Photo updated for this session.");};image.onerror=()=>setNotice("Could not open this image.");image.src=source;};reader.onerror=()=>setNotice("Could not open this photo.");reader.readAsDataURL(file);};
 return <div className="personal-profile-background min-h-screen"><div className="insight-shell">
 {menu&&<button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" aria-label="Close navigation overlay" onClick={()=>setMenu(false)}/>}
 <WorkspaceSidebar active="My Profile" open={menu} onClose={()=>setMenu(false)} onSelect={label=>{if(label==="Dashboard")navigate({to:"/"});else if(label==="My Project")navigate({to:"/project"});else if(label==="3D Lab")navigate({to:"/lab"});else if(label==="Component Catalog")navigate({to:"/catalog"});else if(label==="Reports")navigate({to:"/project",search:{tab:"reports"}});else if(label==="Team")navigate({to:"/project",search:{tab:"team"}});else if(label==="Inventory")navigate({to:"/project",search:{tab:"components"}});}} className="lg:sticky lg:top-4 lg:h-[calc(100vh-32px)]"/>
 <main className="insight-main personal-profile"><header className="project-page-heading"><div className="flex items-center gap-3"><button className="lg:hidden" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button><div><p className="insight-eyebrow">MY PROFILE / MY PERSONAL SPACE</p><h1>A space that's yours.</h1></div></div><Button className="action-blue-solid" onClick={edit}><Pencil size={14}/>Edit Profile</Button></header>
 <section className="personal-hero"><div className="personal-hero-copy"><span className="personal-kicker"><Sparkles size={14}/>A little room for big ideas</span><h2>Make time.<br/><em>Make something.</em></h2><p>Your details, your thoughts, your next small win.</p></div><div className="personal-desk-art" aria-hidden="true"><div className="desk-notebook"><span>ONE IDEA AT A TIME</span><i/><i/><i/><i/><i/><b>✦</b></div><div className="desk-sticky">a fresh<br/>start ☀</div><div className="desk-pencil"/></div></section>
 {notice&&<p role="status" className="profile-save-notice"><CheckCircle2 size={14}/>{notice}</p>}
 <div className="personal-layout"><div className="personal-main">
 <section className="personal-id-card"><div className="personal-id-heading"><div className="profile-avatar-wrap"><img src={profile.photo} alt={`${profile.name} profile photo`}/><button aria-label="Change profile photo" onClick={()=>photoInput.current?.click()}><Camera size={15}/></button><input ref={photoInput} className="sr-only" aria-label="Choose profile photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{readPhoto(e.target.files?.[0]);e.target.value="";}}/></div><div><span className="personal-kicker">THE BASICS</span><h2>My information</h2><p>Keep your student details up to date.</p></div><button className="personal-edit" aria-label="Edit personal information" onClick={edit}><Pencil size={16}/></button></div>
 <dl className="personal-details">{fields.map(f=><div key={f.key}><f.icon size={17}/><dt>{f.label}</dt><dd>{profile[f.key]||<button onClick={edit}>Add details <Plus size={11}/></button>}</dd></div>)}</dl>
 <div className="personal-github"><Github size={23}/><div><strong>GitHub</strong><p>{github?new URL(github).pathname.slice(1):"Connect your coding space"}</p></div>{github?<a href={github} target="_blank" rel="noopener noreferrer" aria-label="Open GitHub profile"><ArrowUpRight size={18}/></a>:<button onClick={edit}>Add link</button>}</div></section>
 <section className="personal-notebook"><div className="insight-section-heading"><div><p className="insight-eyebrow">THOUGHTS, IDEAS & LITTLE PLANS</p><h2>My notebook</h2></div><StickyNote size={23}/></div><label className="sr-only" htmlFor="personal-note">Personal notes</label><textarea id="personal-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={6000} placeholder="An idea I don't want to forget…\nSomething to try, something to learn, or just a thought."/><footer><span>{note.length}/6000</span><span><Check size={12}/>Kept for this session</span></footer></section>
 </div><aside className="personal-side">
 <section className="personal-completion"><div className="insight-section-heading"><h2>Profile completeness</h2><Sparkles size={18}/></div><div className="personal-completion-content"><ProgressRing value={completion} size={90} label="Profile completeness"/><div><strong>{completion===100?"All set!":"A little more you."}</strong><p>{fields.filter(f=>!profile[f.key].trim()).length} details left to add</p><button onClick={edit}>Update details <ArrowRight size={12}/></button></div></div></section>
 <section className="personal-today"><div className="insight-section-heading"><div><p className="insight-eyebrow">MY OWN LITTLE CHECKLIST</p><h2>For today</h2></div><span className="personal-task-count">{tasks.filter(t=>t.done).length}/{tasks.length}</span></div>
 {!tasks.length&&<p className="personal-empty">Start with one small thing you'd like to finish today.</p>}
 <ul className="personal-task-list">{tasks.map(t=><li key={t.id}><button className={`personal-check ${t.done?"is-done":""}`} aria-label={`Complete ${t.text}`} aria-pressed={t.done} onClick={()=>setTasks(tasks.map(item=>item.id===t.id?{...item,done:!item.done}:item))}>{t.done&&<Check size={12}/>}</button><span className={t.done?"is-finished":""}>{t.text}</span><button className="personal-delete" aria-label={`Delete ${t.text}`} onClick={()=>setTasks(tasks.filter(item=>item.id!==t.id))}><Trash2 size={13}/></button></li>)}</ul>
 <form className="personal-add" onSubmit={e=>{e.preventDefault();if(!taskText.trim())return;setTasks([...tasks,{id:crypto.randomUUID(),text:taskText.trim(),done:false}]);setTaskText("");}}><input aria-label="New personal task" placeholder="Add something for today…" value={taskText} maxLength={200} onChange={e=>setTaskText(e.target.value)}/><button aria-label="Add personal task" disabled={!taskText.trim()}><Plus size={18}/></button></form></section>
 <section className="personal-reminders"><div className="insight-section-heading"><h2><Bell size={17}/>A reminder to myself</h2></div><ul>{reminders.map(r=><li key={r.id}><span><strong>{r.text}</strong><small>{new Date(r.when).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></span><button className="personal-delete" aria-label={`Delete reminder ${r.text}`} onClick={()=>setReminders(reminders.filter(item=>item.id!==r.id))}><Trash2 size={13}/></button></li>)}</ul><form onSubmit={e=>{e.preventDefault();if(!reminderText.trim()||!when)return;setReminders([...reminders,{id:crypto.randomUUID(),text:reminderText.trim(),when}].sort((a,b)=>a.when.localeCompare(b.when)));setReminderText("");setWhen("");}}><input aria-label="Reminder text" value={reminderText} onChange={e=>setReminderText(e.target.value)} placeholder="Remember to…" maxLength={200} required/><div><input type="datetime-local" aria-label="Reminder date and time" value={when} onChange={e=>setWhen(e.target.value)} required/><button aria-label="Add reminder"><Plus size={17}/></button></div></form><p className="personal-fineprint">Saved here for your reference; no notifications are sent.</p></section>
 <section className="personal-people"><p className="insight-eyebrow">THE PEOPLE AROUND MY PROJECT</p><div><span>Supervisor</span><strong>Dr. Lina Hassan</strong></div><div><span>Teammates</span><p>{teammates.slice(1).map(t=><span key={t.name}>{t.name}</span>)}</p></div></section>
 </aside></div><p className="personal-fineprint personal-session">Your personal space · Changes stay during this session.</p></main></div>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="profile-edit-dialog max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Edit Profile</DialogTitle><DialogDescription>Your basic information and GitHub link.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(draft.github.trim()&&!safeProfileLink(draft.github)){setError("Use an http or https address for GitHub.");return;}updateProfile({...draft,name:draft.name.trim(),github:draft.github.trim(),photo:profile.photo});setEditing(false);setNotice("Profile updated for this session.");}}><div className="profile-edit-fields">{fields.map(f=><label key={f.key} htmlFor={`profile-${f.key}`}>{f.label}<input id={`profile-${f.key}`} type={f.type} value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:e.target.value})} required={f.key==="name"} min={f.key==="birthYear"?1900:undefined} max={f.key==="birthYear"?new Date().getFullYear():undefined} step={f.key==="birthYear"?1:undefined} maxLength={f.key==="name"?80:200}/></label>)}<label htmlFor="profile-github">GitHub URL<input id="profile-github" type="url" value={draft.github} onChange={e=>setDraft({...draft,github:e.target.value})} maxLength={250}/></label></div>{error&&<p role="alert" className="text-destructive text-xs mt-3">{error}</p>}<div className="profile-edit-footer"><Button type="button" variant="secondary" onClick={()=>setEditing(false)}>Cancel</Button><Button className="action-blue-solid" type="submit" disabled={!draft.name.trim()}>Save Profile</Button></div></form></DialogContent></Dialog></div>;
}
