import { WorkspaceSidebar } from "@/components/WorkspaceSidebar";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { componentCatalog, readBom } from "@/lib/componentCatalog";
import { ArrowUpRight, Box, Check, CheckCircle2, CircleAlert, Cpu, FileText, FolderKanban, LayoutDashboard, Package, Plus, Users, Wallet, X, Menu, CalendarDays, MessageSquare, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import avatar from "@/assets/student-avatar.jpg";

export const Route = createFileRoute("/project")({
  validateSearch: (search: Record<string, unknown>): { action?: "issue" | "report" | "bom" } => search["action"] === "issue" || search["action"] === "report" || search["action"] === "bom" ? { action: search["action"] } : {},
  head: () => ({ meta: [{ title: "My Project | HardwareMate AI" }] }),
  component: ProjectPage,
});

const team = [
  { name: "NOOR OWASSI", initials: "NO", progress: 76, done: 19, remaining: 6, tasks: ["Finalize sensor connections", "Document circuit changes"], tone: "mint" },
  { name: "Omar Khalil", initials: "OK", progress: 68, done: 17, remaining: 8, tasks: ["Test motor driver response", "Check power consumption"], tone: "blue" },
  { name: "Lina Nasser", initials: "LN", progress: 64, done: 16, remaining: 9, tasks: ["Calibrate obstacle detection", "Record test results"], tone: "rose" },
  { name: "Ahmad Saleh", initials: "AS", progress: 64, done: 16, remaining: 9, tasks: ["Review component costs", "Prepare prototype enclosure"], tone: "amber" },
];
const upcoming = [
  { title: "Finalize circuit schematic", date: "Oct 08, 2026", owner: "NOOR & Omar", tag: "Design" },
  { title: "Test obstacle detection", date: "Oct 11, 2026", owner: "Lina & Ahmad", tag: "Testing" },
  { title: "Prototype demonstration", date: "Oct 24, 2026", owner: "Whole team", tag: "Milestone" },
];
const initialBom = [{ name: "Arduino Uno", quantity: 1, cost: 22, available: true }, { name: "L298N Motor Driver", quantity: 1, cost: 8, available: true }, { name: "HC-SR04 Ultrasonic Sensor", quantity: 2, cost: 8, available: false }, { name: "18650 Li-ion Battery", quantity: 1, cost: 6, available: false }];

function Panel({ title, subtitle, icon: Icon, children, className = "" }: { title: string; subtitle?: string; icon: typeof Users; children: ReactNode; className?: string }) {
  return <section className={`glass-panel project-panel rounded-[20px] p-5 ${className}`}><div className="mb-4 flex items-center gap-2.5"><span className="project-section-icon"><Icon size={18} /></span><div><h2 className="text-sm font-bold">{title}</h2>{subtitle && <p className="mt-0.5 text-[11px] text-muted-foreground">{subtitle}</p>}</div></div>{children}</section>;
}

function ProjectPage() {
  const [bom, setBom] = useState(initialBom);
  useEffect(() => {
    const merged = initialBom.map(item => ({...item}));
    readBom().forEach(entry => { const component=componentCatalog.find(item=>item.key===entry.key)!; const existing=merged.find(item=>item.name===component.name); if(existing) existing.quantity+=entry.quantity; else merged.push({name:component.name,quantity:entry.quantity,cost:0,available:false}); });
    setBom(merged);
  }, []);
  const navigate = useNavigate();
  const search = Route.useSearch();
  const [abstract, setAbstract] = useState("We\u0027re developing an autonomous smart car that detects obstacles and navigates safely using ultrasonic sensors, an Arduino controller, and a dual motor driver. Our goal is to combine reliable sensing, efficient power management, and responsive motor control into an affordable, compact prototype. The expected result is a working vehicle that identifies obstacles in real time, adjusts its path, and demonstrates the practical use of embedded systems in autonomous navigation.");
  const [abstractDraft, setAbstractDraft] = useState("");
  const [menu, setMenu] = useState(false);
  const [modal, setModal] = useState<"bom" | "issue" | "report" | "abstract" | null>(search.action ?? null);
  const [issues, setIssues] = useState<string[]>([]);
  const [draft, setDraft] = useState("");
  const [report, setReport] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [doneTasks, setDoneTasks] = useState<string[]>([]);
  const toggleTask = (id: string) => setDoneTasks(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  return <div className="dashboard-background project-background min-h-screen">
    <div className="mx-auto flex max-w-[1800px] gap-4 p-3 lg:p-4">
      {menu && <button aria-label="Close navigation overlay" onClick={() => setMenu(false)} className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" />}
      <WorkspaceSidebar active="My Project" open={menu} onClose={() => setMenu(false)} onSelect={label => { if(label === "Dashboard") navigate({to:"/"}); else if(label === "3D Lab") navigate({to:"/lab"}); else if(label === "Reports") setModal("report"); else if(label === "Component Catalog") navigate({to:"/catalog"}); else if(label === "Inventory") setModal("bom"); else if(label === "Team") document.getElementById("project-team")?.scrollIntoView({behavior:"smooth"}); else if(label !== "My Project") navigate({to:"/"}); }} className="lg:sticky lg:top-4 lg:h-[calc(100vh-32px)]" />
      <main className="min-w-0 flex-1 space-y-4 pb-5">
        <header className="flex items-center justify-between px-1 py-2"><div className="flex items-center gap-3"><button onClick={() => setMenu(true)} aria-label="Open menu" className="lg:hidden"><Menu /></button><div><p className="text-[11px] text-muted-foreground">Workspace / My Project</p><h1 className="mt-1 text-xl font-bold">My Project</h1></div></div><span className="project-badge"><span className="size-1.5 rounded-full bg-primary" />One team. One shared goal.</span></header>
        <section className="glass-panel project-hero relative overflow-hidden rounded-[22px] p-5 sm:p-6">
          <div className="relative z-10 flex flex-wrap items-start justify-between gap-4"><div><span className="project-eyebrow">HARDWARE IN ACTION</span><h2 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Smart Car <span className="font-medium text-muted-foreground">— Autonomous Navigation</span></h2><p className="mt-2 max-w-xl text-xs leading-relaxed text-muted-foreground">From our first circuit to a working prototype. Everything we're building, together.</p><div className="mt-4 flex flex-wrap gap-2"><span className="project-badge">In Progress</span><span className="project-neutral-badge"><CalendarDays size={12} />Due Oct 24, 2026</span><span className="project-neutral-badge"><Users size={12} />4 teammates</span></div></div><div className="project-progress-summary"><span className="text-3xl font-extrabold text-primary">68<span className="text-lg">%</span></span><span className="text-[10px] text-muted-foreground">Overall progress</span><div className="progress-track mt-2 h-1.5 w-28 rounded-full"><div className="progress-fill h-1.5 w-[68%] rounded-full" /></div></div></div>
        </section>
        <section className="glass-panel project-abstract rounded-[20px] p-5 sm:p-6"><div className="flex items-start gap-4"><span className="project-abstract-icon"><CircuitIcon /></span><div className="min-w-0 flex-1"><span className="project-eyebrow">THE IDEA BEHIND THE BUILD</span><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="mt-1 text-lg font-bold">Project Abstract</h2><Button variant="secondary" size="sm" onClick={() => { setAbstractDraft(abstract); setModal("abstract"); }}>Edit Abstract</Button></div><p className="mt-3 max-w-5xl whitespace-pre-wrap break-words text-sm leading-7 text-foreground/80">{abstract}</p></div></div></section>
        <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[
          { icon: Target, label: "Project Progress", value: "68%", detail: "Building toward our final demo" },
          { icon: CheckCircle2, label: "Current Milestone", value: "Prototype Testing", detail: "Milestone 3 of 5" },
          { icon: CircleAlert, label: "Open Issues", value: String(3 + issues.length), detail: issues.length ? "New issues added to this session" : "2 hardware · 1 software" },
          { icon: Wallet, label: "Budget Status", value: "$184 / $250", detail: "$66 remaining · On track" },
        ].map(stat => <div key={stat.label} className="glass-panel flex min-w-0 items-center gap-3 rounded-2xl p-4"><span className="project-stat-icon"><stat.icon size={20} /></span><div className="min-w-0"><p className="text-[10px] text-muted-foreground">{stat.label}</p><p className="mt-1 text-base font-bold">{stat.value}</p><p className="mt-1 text-[10px] text-muted-foreground">{stat.detail}</p></div></div>)}</div>
        <div id="project-team"><Panel title="Our Team" subtitle="Shared ownership. Individual progress. Built together." icon={Users}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{team.map((person, index) => {
          const checked = person.tasks.filter((_, task) => doneTasks.includes(`${index}-${task}`)).length;
          return <article key={person.name} className={`glass-inset project-team-card project-tone-${person.tone} rounded-2xl p-4`}><div className="flex items-center gap-2.5">{index === 0 ? <img src={avatar} alt={person.name} className="size-10 rounded-full object-cover" /> : <svg role="img" aria-label={`${person.name} avatar`} viewBox="0 0 48 48" className="project-team-avatar size-10 shrink-0"><circle cx="24" cy="24" r="24" fill="currentColor" /><text x="24" y="29" textAnchor="middle" fontSize="15" fill="white" fontFamily="sans-serif" fontWeight="bold">{person.initials}</text></svg>}<div><h3 className="text-xs font-bold">{person.name}</h3><p className="mt-0.5 text-[10px] text-muted-foreground">{person.done + checked} completed · {person.remaining - checked} remaining</p></div></div><div className="mb-2 mt-4 flex justify-between text-[11px]"><span className="text-muted-foreground">Personal progress</span><strong className="text-primary">{Math.round((person.done + checked) / (person.done + person.remaining) * 100)}%</strong></div><div className="progress-track h-1.5 rounded-full"><div className="progress-fill h-1.5 rounded-full transition-all" style={{ width: `${(person.done + checked) / (person.done + person.remaining) * 100}%` }} /></div><p className="mb-2 mt-4 text-[10px] font-semibold text-muted-foreground">TODAY'S TASKS</p><div className="space-y-2">{person.tasks.map((task, taskIndex) => {const id = `${index}-${taskIndex}`, done = doneTasks.includes(id); return <button key={task} onClick={() => toggleTask(id)} aria-pressed={done} className="flex w-full items-start gap-2 text-left text-[11px] leading-4"><span className={`project-task-checkbox ${done ? "project-task-done" : ""}`}>{done && <Check size={10} />}</span><span className={done ? "text-muted-foreground line-through" : ""}>{task}</span></button>;})}</div></article>;
        })}</div></Panel></div>
        <div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]">
          <Panel title="Upcoming Tasks & Deadlines" subtitle="What's next for our project" icon={CalendarDays}><div className="space-y-2">{upcoming.map(task => <div key={task.title} className="glass-inset flex items-center justify-between gap-3 rounded-xl p-3"><div className="flex items-center gap-3"><span className="project-section-icon"><CheckCircle2 size={16} /></span><div><p className="text-xs font-semibold">{task.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{task.owner} · {task.tag}</p></div></div><span className="whitespace-nowrap text-[10px] font-medium text-primary">{task.date}</span></div>)}</div></Panel>
          <Panel title="Missing Components" subtitle="Two items to complete our prototype" icon={Package}><div className="space-y-3">{[{name:"HC-SR04 Ultrasonic Sensor",image:"/components/hc-sr04.jpg",qty:"2 needed",cost:"$8 estimated"},{name:"18650 Li-ion Battery",image:"/components/battery-18650.jpg",qty:"1 needed",cost:"$6 estimated"}].map(item => <div key={item.name} className="glass-inset flex items-center gap-3 rounded-xl p-3"><img src={item.image} alt={item.name} className="h-12 w-16 rounded-lg bg-white object-contain p-1" /><div className="flex-1"><p className="text-xs font-semibold">{item.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.qty} · {item.cost}</p></div><span className="project-neutral-badge">Missing</span></div>)}</div></Panel>
          <Panel title="Latest Supervisor Feedback" icon={MessageSquare}><div className="flex gap-3"><span className="project-section-icon shrink-0 text-base font-bold">LH</span><div><p className="text-xs font-bold">Dr. Lina Hassan</p><time className="text-[10px] text-muted-foreground" dateTime="2026-10-03">Oct 03, 2026</time><blockquote className="mt-3 border-l-2 border-primary/30 pl-3 text-xs leading-6 text-foreground/80">“Good progress on the prototype. Please verify the sensor readings under different lighting conditions and include a power consumption comparison in your next weekly report.”</blockquote></div></div></Panel>
          <Panel title="Weekly Report Status" icon={FileText}><div className="glass-inset flex items-center justify-between rounded-xl p-3"><div><p className="text-xs font-bold">Week 06 · Prototype Testing</p><p className="mt-1 text-[10px] text-muted-foreground">Due Oct 09, 2026</p></div><span className="project-badge">{submitted ? "Submitted" : "Pending"}</span></div><p className="mt-3 text-[11px] leading-5 text-muted-foreground">{submitted ? "Your report has been marked as submitted in this session." : "Share this week's progress, test results, and any blockers with your supervisor."}</p><button onClick={() => setModal("report")} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary">{submitted ? "View report" : "Prepare weekly report"}<ArrowUpRight size={13} /></button></Panel>
        </div>
        <div className="glass-panel flex flex-wrap items-center justify-between gap-3 rounded-[20px] p-4"><div><h2 className="text-sm font-bold">Keep the project moving</h2><p className="mt-1 text-[11px] text-muted-foreground">Your next step, one click away.</p></div><div className="flex flex-wrap gap-2"><Button asChild size="sm"><Link to="/lab"><Box size={15} />Open 3D Lab</Link></Button><Button variant="secondary" size="sm" onClick={() => setModal("bom")}><Package size={15} />View BOM</Button><Button variant="secondary" size="sm" onClick={() => setModal("issue")}><Plus size={15} />Add Issue</Button><Button variant="secondary" size="sm" onClick={() => setModal("report")}><FileText size={15} />Submit Weekly Report</Button></div></div>
        {issues.length > 0 && <Panel title="Issues added this session" icon={CircleAlert}>{issues.map((issue,i)=><p key={i} className="mt-2 text-xs">{issue}</p>)}</Panel>}
      </main>
    </div>
    <Dialog open={modal !== null} onOpenChange={open => !open && setModal(null)}><DialogContent className="glass-panel glass-strong"><DialogHeader><DialogTitle>{modal === "abstract" ? "Edit Project Abstract" : modal === "bom" ? "Bill of Materials" : modal === "issue" ? "Add Issue" : "Weekly Report"}</DialogTitle><DialogDescription>{modal === "abstract" ? "Describe your project idea, goals, and expected result. Save to update the page." : modal === "bom" ? "Components for your Smart Car prototype." : "Changes are kept locally in this session."}</DialogDescription></DialogHeader>
      {modal === "abstract" && <form onSubmit={e => { e.preventDefault(); if (!abstractDraft.trim()) return; setAbstract(abstractDraft.trim()); setModal(null); }} className="space-y-4"><label htmlFor="abstract-editor" className="text-xs font-semibold">Project abstract</label><textarea id="abstract-editor" autoFocus required value={abstractDraft} onChange={e => setAbstractDraft(e.target.value)} className="glass-inset min-h-72 max-h-[55vh] w-full resize-y rounded-xl p-4 text-sm leading-7 outline-none focus:ring-2 focus:ring-ring/40" /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" disabled={!abstractDraft.trim()}>Save Changes</Button></div></form>}
      {modal === "bom" && <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border"><th className="py-3">Component</th><th>Qty</th><th>Cost</th><th>Status</th></tr></thead><tbody>{bom.map(item=><tr key={item.name} className="border-b border-border/50"><td className="py-3">{item.name}</td><td>{item.quantity}</td><td>{item.cost ? `$${item.cost}` : "—"}</td><td>{item.available ? "Available" : "Missing"}</td></tr>)}</tbody></table></div>}
      {modal === "issue" && <form onSubmit={e=>{e.preventDefault();if(!draft.trim())return;setIssues(current=>[...current,draft.trim()]);setDraft("");setModal(null);}} className="space-y-3"><label htmlFor="project-issue" className="text-xs font-semibold">Issue description</label><textarea id="project-issue" required value={draft} onChange={e=>setDraft(e.target.value)} className="glass-inset min-h-28 w-full rounded-xl p-3 text-sm" placeholder="Describe the issue and its impact…" /><Button type="submit" disabled={!draft.trim()}>Add Issue</Button></form>}
      {modal === "report" && <form onSubmit={e=>{e.preventDefault();if(!report.trim())return;setSubmitted(true);setModal(null);}} className="space-y-3"><label htmlFor="weekly-summary" className="text-xs font-semibold">Progress, test results & blockers</label><textarea id="weekly-summary" required value={report} onChange={e=>setReport(e.target.value)} className="glass-inset min-h-36 w-full rounded-xl p-3 text-sm" placeholder="What did your team accomplish this week?" readOnly={submitted} /><Button disabled={submitted || !report.trim()} type="submit">{submitted ? "Report Submitted" : "Submit Weekly Report"}</Button></form>}
    </DialogContent></Dialog>
  </div>;
}

function CircuitIcon() { return <Cpu size={26} strokeWidth={1.5} />; }
