import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleAlert, FileText, Layers, Menu, MessageSquare, Package, Pencil, Plus, Send, Users, Wallet } from "lucide-react";
import { WorkspaceSidebar } from "@/components/WorkspaceSidebar";
import { ProjectMedia } from "@/components/ProjectMedia";
import { MilestonePath, ProgressRing } from "@/components/ProjectVisuals";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { deadlines, project, projectBom, teammates, useProjectWorkspace } from "@/lib/projectWorkspace";
import { componentCatalog, readBom } from "@/lib/componentCatalog";
import { useStudentProfile } from "@/lib/studentProfile";

type ProjectTab = "overview" | "team" | "components" | "reports";
type ProjectAction = "issue" | "report" | "bom";
export const Route = createFileRoute("/project")({
  validateSearch: (search: Record<string, unknown>): { tab?: ProjectTab; action?: ProjectAction } => ({ ...(["overview","team","components","reports"].includes(String(search["tab"])) ? {tab:search["tab"] as ProjectTab}:{}), ...(["issue","report","bom"].includes(String(search["action"])) ? {action:search["action"] as ProjectAction}:{}) }),
  head: () => ({ meta: [{ title: "My Project | HardwareMate AI" }] }), component: ProjectPage,
});
function ProjectPage() {
  const navigate=useNavigate(), search=Route.useSearch(), workspace=useProjectWorkspace();
  const {profile}=useStudentProfile(), avatar=profile.photo;
  const [menu,setMenu]=useState(false), [tab,setTab]=useState<ProjectTab>(search.tab ?? (search.action==="report"?"reports":search.action==="bom"?"components":"overview"));
  const [modal,setModal]=useState<"abstract"|"issue"|null>(search.action==="issue"?"issue":null), [abstractDraft,setAbstractDraft]=useState(""), [issueDraft,setIssueDraft]=useState("");
  const [bom,setBom]=useState<{name:string;quantity:number;cost:number;available:boolean;image?:string}[]>(projectBom);
  useEffect(()=>{
    const merged:typeof bom=projectBom.map(item=>({...item}));
    readBom().forEach(entry=>{const component=componentCatalog.find(item=>item.key===entry.key);if(!component)return;const existing=merged.find(item=>item.name===component.name);if(existing)existing.quantity+=entry.quantity;else merged.push({name:component.name,quantity:entry.quantity,cost:0,available:false});});setBom(merged);
  },[]);
  useEffect(()=>{setTab(search.tab ?? (search.action==="report"?"reports":search.action==="bom"?"components":"overview"));if(search.action==="issue")setModal("issue");},[search.tab,search.action]);
  const missing=bom.filter(item=>!item.available), unitCount=bom.reduce((sum,item)=>sum+item.quantity,0), availableUnits=bom.filter(item=>item.available).reduce((sum,item)=>sum+item.quantity,0);
  const selectTab=(value:ProjectTab)=>{setTab(value);navigate({to:"/project",search:{tab:value},replace:true});};
  return <div className="dashboard-background project-background min-h-screen"><div className="insight-shell">
    {menu&&<button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" aria-label="Close navigation overlay" onClick={()=>setMenu(false)}/>}
    <WorkspaceSidebar active="My Project" open={menu} onClose={()=>setMenu(false)} onSelect={label=>{if(label==="Dashboard")navigate({to:"/"});else if(label==="Team")selectTab("team");else if(label==="Inventory")selectTab("components");else if(label==="Reports")selectTab("reports");else if(label==="3D Lab")navigate({to:"/lab"});else if(label==="Component Catalog")navigate({to:"/catalog"});}} className="lg:sticky lg:top-4 lg:h-[calc(100vh-32px)]"/>
    <main className="insight-main">
      <header className="project-page-heading"><div className="flex items-center gap-3"><button className="lg:hidden" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button><div><p className="insight-eyebrow">WORKSPACE / MY PROJECT</p><h1>Your idea. Taking shape.</h1></div></div><button className="insight-text-link" onClick={()=>navigate({to:"/"})}>Workspace overview<ArrowUpRight size={14}/></button></header>
      <section className="insight-paper project-cover"><div className="project-cover-copy"><span className="project-badge"><span className="insight-dot"/>{project.status}</span><h2>{project.name}<span>{project.subtitle}</span></h2><p className="project-cover-meta"><span><CalendarDays size={14}/>{project.deadline}</span><span><Users size={14}/>{teammates.length} teammates</span></p><div className="project-cover-actions"><Button size="sm" className="action-blue-solid" onClick={()=>selectTab("reports")}><FileText size={14}/>Weekly report</Button><Button size="sm" variant="secondary" className="action-orange-soft" onClick={()=>setModal("issue")}><Plus size={14}/>Add issue</Button></div></div><div className="project-cover-progress"><ProgressRing value={workspace.progress} size={116} label="Overall project progress"/><span>{workspace.completedCount} / {workspace.taskCount} tasks complete</span></div><ProjectMedia/></section>
      <Tabs value={tab} onValueChange={value=>selectTab(value as ProjectTab)} className="project-workspace-tabs">
        <TabsList className="project-tab-list" aria-label="Project sections"><TabsTrigger value="overview"><Layers size={15}/>Overview</TabsTrigger><TabsTrigger value="team"><Users size={15}/>Team & Tasks</TabsTrigger><TabsTrigger value="components"><Package size={15}/>Components<span>{missing.length}</span></TabsTrigger><TabsTrigger value="reports"><FileText size={15}/>Reports<span className={workspace.submitted?"project-report-dot is-submitted":"project-report-dot"}/></TabsTrigger></TabsList>
        <TabsContent value="overview" className="project-tab-panel">
          <div className="project-overview-grid">
            <section className="insight-paper project-abstract-editor"><div className="insight-section-heading"><div><p className="insight-eyebrow">THE IDEA BEHIND THE BUILD</p><h2>Project Abstract</h2></div><Button variant="ghost" size="sm" className="action-blue-soft" onClick={()=>{setAbstractDraft(workspace.abstract);setModal("abstract");}}><Pencil size={13}/>Edit Abstract</Button></div><p className="project-abstract-copy">{workspace.abstract}</p><div className="project-outcome"><span className="tone-blue insight-color-icon"><Layers size={18}/></span><div><strong>The next checkpoint</strong><p>Prototype testing · milestone {project.milestone} of {project.milestoneCount}</p></div></div></section>
            <section className="insight-paper project-budget-analysis"><div className="insight-section-heading"><h2>Budget health</h2><Wallet size={17} className="text-muted-foreground"/></div><div className="budget-orbit"><ProgressRing value={project.spent/project.budget*100} size={120} label="Budget used"/><div><strong>${project.budget-project.spent}</strong><span>still available</span></div></div><div className="budget-legend"><span><i/>Spent <strong>${project.spent}</strong></span><span><i/>Remaining <strong>${project.budget-project.spent}</strong></span></div><p className="insight-fineprint">Total project budget: ${project.budget}. Recorded expenses across the project.</p></section>
          </div>
          <section className="insight-paper project-stage-panel"><MilestonePath/></section>
          <section className="project-snapshot" aria-label="Project health"><button onClick={()=>selectTab("components")} className="tone-orange"><span className="insight-color-icon"><Package size={19}/></span><div><strong>{missing.length} component types missing</strong><p>Review what the prototype still needs.</p></div><ArrowRight size={15}/></button><button onClick={()=>selectTab("reports")} className="tone-blue"><span className="insight-color-icon"><MessageSquare size={19}/></span><div><strong>Latest supervisor feedback</strong><p>Dr. Lina Hassan · Oct 03</p></div><ArrowRight size={15}/></button><button onClick={()=>setModal("issue")} className="tone-purple"><span className="insight-color-icon"><CircleAlert size={19}/></span><div><strong>{3+workspace.issues.length} open issues</strong><p>2 hardware · 1 software{workspace.issues.length?` · ${workspace.issues.length} new`:""}</p></div><Plus size={15}/></button></section>
          {workspace.issues.length>0&&<section className="insight-paper"><h2 className="text-sm font-bold">Issues recorded this session</h2><ul className="insight-issue-list">{workspace.issues.map((issue,i)=><li key={i}><CircleAlert size={15}/>{issue}</li>)}</ul></section>}
        </TabsContent>
        <TabsContent value="team" className="project-tab-panel" id="project-team">
          <section className="insight-paper team-workspace"><div className="insight-section-heading"><div><p className="insight-eyebrow">SHARED OWNERSHIP. INDIVIDUAL MOMENTUM.</p><h2>Our team</h2></div><span className="project-badge">{workspace.completedCount} tasks complete</span></div><div className="team-workspace-list">{teammates.map((person,index)=>{const displayName=index===0?profile.name:person.name;const checked=person.tasks.filter((_,i)=>workspace.completed.includes(`${index}-${i}`)).length;const progress=(person.done+checked)/(person.done+person.remaining)*100;return <article key={person.name} className={`team-workspace-row project-tone-${person.tone}`}><div className="team-person">{index===0?<img src={avatar} alt=""/>:<span className={`insight-person-initials tone-${person.tone==="rose"?"orange":person.tone==="amber"?"purple":"blue"}`}>{person.initials}</span>}<div><h3>{displayName}</h3><p>{person.done+checked} completed · {person.remaining-checked} remaining</p></div></div><div className="team-person-progress"><ProgressRing value={progress} size={72} label={`${displayName} personal progress`}/><span>Personal progress</span></div><div className="team-person-tasks"><p>Today's tasks</p>{person.tasks.map((task,i)=>{const done=workspace.completed.includes(`${index}-${i}`);return <button key={task} aria-pressed={done} onClick={()=>workspace.toggleTask(`${index}-${i}`)}><span className={`insight-task-check ${done?"is-done":""}`}>{done&&<Check size={12}/>}</span><span className={done?"line-through text-muted-foreground":""}>{task}</span></button>})}</div></article>})}</div></section>
          <section className="insight-paper"><div className="insight-section-heading"><h2>Upcoming Tasks & Deadlines</h2><CalendarDays size={18} className="text-muted-foreground"/></div><div className="project-deadline-list">{deadlines.filter(item=>item.type!=="Report").map(item=><div key={item.name} className={`tone-${item.tone}`}><span className="insight-date"><small>{item.month}</small><strong>{item.day}</strong></span><div><strong>{item.name}</strong><p>{item.owner} · {item.type}</p></div><span>{item.date}</span></div>)}<div className="tone-purple"><span className="insight-date"><small>OCT</small><strong>24</strong></span><div><strong>Prototype demonstration</strong><p>Whole team · Final milestone</p></div><span>{project.deadline}</span></div></div></section>
        </TabsContent>
        <TabsContent value="components" className="project-tab-panel">
          <div className="components-workspace-grid"><section className="insight-paper"><div className="insight-section-heading"><div><p className="insight-eyebrow">WHAT THE BUILD IS MADE OF</p><h2>Bill of Materials</h2></div><span className="insight-count-pill">{unitCount} units</span></div><div className="project-bom-scroll"><table className="project-bom-table"><thead><tr><th>Component</th><th>Qty</th><th>Listed cost</th><th>Availability</th></tr></thead><tbody>{bom.map(item=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.quantity}</td><td>{item.cost?`$${item.cost}`:"—"}</td><td><span className={item.available?"project-badge":"project-badge action-orange-soft"}>{item.available?"Available":"Missing"}</span></td></tr>)}</tbody></table></div><p className="insight-fineprint">Listed costs are estimates for these items, not the full project expenditure.</p><Button variant="secondary" size="sm" onClick={()=>navigate({to:"/catalog"})} className="mt-4 action-blue-soft">Explore component catalog<ArrowUpRight size={13}/></Button></section><section className="insight-paper component-readiness"><h2>Build readiness</h2><ProgressRing value={unitCount?availableUnits/unitCount*100:0} size={132} label="Available component units"/><strong>{availableUnits} / {unitCount} units available</strong><p>{unitCount-availableUnits} units still needed for the listed build.</p></section></div>
          <section className="insight-paper"><div className="insight-section-heading"><h2>Missing Components</h2><span className="project-badge action-orange-soft">{missing.length} types</span></div><div className="project-missing-grid">{missing.map(item=><article key={item.name}>{item.image?<img src={item.image} alt={item.name}/>:<span className="insight-color-icon tone-orange"><Package size={28}/></span>}<div><h3>{item.name}</h3><p>{item.quantity} needed{item.cost?` · $${item.cost} estimated`:""}</p></div><span className="insight-needed-count">×{item.quantity}</span></article>)}</div></section>
        </TabsContent>
        <TabsContent value="reports" className="project-tab-panel">
          <div className="project-reports-grid"><section className="insight-paper weekly-report-workspace"><div className="insight-section-heading"><div><p className="insight-eyebrow">YOUR WEEK, DOCUMENTED</p><h2>Weekly Report Status</h2></div><span className={workspace.submitted?"project-badge":"project-badge action-orange-soft"}>{workspace.submitted?"Submitted":"Pending"}</span></div><div className="weekly-document-heading"><span className="report-document-icon"><FileText size={34}/></span><div><strong>Week 06</strong><p>Prototype Testing · Due Oct 09, 2026</p></div></div><form onSubmit={e=>{e.preventDefault();if(workspace.report.trim())workspace.submitReport();}}><label htmlFor="weekly-summary">Progress, test results & blockers</label><textarea id="weekly-summary" value={workspace.report} onChange={e=>workspace.setReport(e.target.value)} placeholder="What did you build or test? What needs attention next?" readOnly={workspace.submitted}/><div className="report-submit-row"><span>Local session preview</span><Button type="submit" size="sm" className="action-blue-solid" disabled={workspace.submitted||!workspace.report.trim()}><Send size={14}/>{workspace.submitted?"Report Submitted":"Submit Weekly Report"}</Button></div></form></section><section className="insight-paper supervisor-note"><p className="insight-eyebrow">A NOTE FROM YOUR SUPERVISOR</p><h2>Latest Supervisor Feedback</h2><span className="supervisor-quote-mark" aria-hidden="true">“</span><blockquote>Good progress on the prototype. Please verify the sensor readings under different lighting conditions and include a power consumption comparison in your next weekly report.</blockquote><div className="supervisor-signature"><span>LH</span><p><strong>Dr. Lina Hassan</strong><time dateTime="2026-10-03">Oct 03, 2026</time></p></div></section></div>
        </TabsContent>
      </Tabs>
      <footer className="project-workspace-footer"><span>One team. One shared goal.</span><button onClick={()=>navigate({to:"/lab"})}>Open 3D Lab<ArrowUpRight size={14}/></button></footer>
    </main>
  </div><Dialog open={modal!==null} onOpenChange={open=>!open&&setModal(null)}><DialogContent className="glass-panel glass-strong"><DialogHeader><DialogTitle>{modal==="abstract"?"Edit Project Abstract":"Add Issue"}</DialogTitle><DialogDescription>Changes stay in your current workspace session.</DialogDescription></DialogHeader>{modal==="abstract"?<form onSubmit={e=>{e.preventDefault();if(!abstractDraft.trim())return;workspace.setAbstract(abstractDraft.trim());setModal(null);}} className="space-y-4"><label htmlFor="abstract-editor" className="text-xs font-semibold">Project abstract</label><textarea id="abstract-editor" autoFocus required value={abstractDraft} onChange={e=>setAbstractDraft(e.target.value)} className="glass-inset min-h-72 max-h-[55vh] w-full resize-y rounded-xl p-4 text-sm leading-7"/><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit" disabled={!abstractDraft.trim()}>Save Changes</Button></div></form>:<form onSubmit={e=>{e.preventDefault();if(!issueDraft.trim())return;workspace.addIssue(issueDraft.trim());setIssueDraft("");setModal(null);}} className="space-y-4"><label htmlFor="project-issue" className="text-xs font-semibold">Issue description</label><textarea id="project-issue" autoFocus required value={issueDraft} onChange={e=>setIssueDraft(e.target.value)} className="glass-inset min-h-28 w-full rounded-xl p-3 text-sm"/><Button type="submit" className="action-orange-soft" disabled={!issueDraft.trim()}>Add Issue</Button></form>}</DialogContent></Dialog></div>;
}
