import { useState } from "react";
import { Box, CalendarDays, Check, CheckCircle2, CircuitBoard, Clock3, Package, ShoppingCart, Wrench } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const inventory = [
  { id: "hc-sr04", name: "HC-SR04 Ultrasonic Sensor", stock: 12, price: 4, location: "Sensors · A2", need: 2, image: "/components/hc-sr04.jpg" },
  { id: "l298n", name: "L298N Motor Driver", stock: 8, price: 8, location: "Drivers · B1", need: 1, image: null },
  { id: "breadboard-400", name: "400-point Breadboard", stock: 18, price: 5, location: "Prototyping · C3", need: 1, image: null },
  { id: "resistor-variable", name: "Resistor Assortment", stock: 24, price: 2, location: "Passives · C1", need: 1, image: null },
];

export function WorkshopDashboard() {
  const [selected, setSelected] = useState<typeof inventory[number] | null>(null);
  const [quantity, setQuantity] = useState(1);
  const [requests, setRequests] = useState<{ id: string; quantity: number }[]>([]);
  const [tasks, setTasks] = useState<string[]>([]);
  const pendingCost = requests.reduce((sum, request) => sum + inventory.find(item => item.id === request.id)!.price * request.quantity, 0);
  return <div className="mt-4 space-y-4">
    <div className="grid gap-3 lg:grid-cols-3">
      <section className="glass-panel rounded-[18px] p-4"><h2 className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 size={17} className="text-primary"/>Your Focus Today</h2><p className="mt-1 text-[11px] text-muted-foreground">Your priorities across the project.</p><div className="mt-4 space-y-3">{["Review team updates", "Finish your assigned task", "Summarize weekly progress"].map(task=><button key={task} onClick={()=>setTasks(current=>current.includes(task)?current.filter(t=>t!==task):[...current,task])} aria-pressed={tasks.includes(task)} className="flex w-full gap-2 text-left text-xs leading-5"><span className={`project-task-checkbox ${tasks.includes(task)?"project-task-done":""}`}>{tasks.includes(task)&&<Check size={10}/>}</span><span className={tasks.includes(task)?"text-muted-foreground line-through":""}>{task}</span></button>)}</div><p className="mt-4 text-[10px] text-primary">{tasks.length} of 3 completed</p></section>
      <section className="glass-panel rounded-[18px] p-4"><h2 className="text-sm font-bold">Coming Up</h2><p className="mt-1 text-[11px] text-muted-foreground">Important deadlines across your workspace.</p><div className="mt-4 space-y-3">{[{title:"Circuit schematic review",date:"Oct 08"},{title:"Weekly progress report",date:"Oct 09"},{title:"Obstacle detection test",date:"Oct 11"}].map(item=><div key={item.title} className="flex justify-between gap-2 text-xs"><span>{item.title}</span><span className="text-primary">{item.date}</span></div>)}</div><Button asChild variant="secondary" size="sm" className="mt-4 w-full"><Link to="/project">View project timeline</Link></Button></section>
      <section className="glass-panel rounded-[18px] p-4"><h2 className="text-sm font-bold">Team at a Glance</h2><p className="mt-1 text-[11px] text-muted-foreground">Equal teammates, shared progress.</p><div className="mt-4 space-y-2">{[{name:"NOOR OWASSI",progress:76},{name:"Omar Khalil",progress:68},{name:"Lina Nasser",progress:64},{name:"Ahmad Saleh",progress:64}].map(person=><div key={person.name}><div className="mb-1 flex justify-between text-[11px]"><span>{person.name}</span><strong className="text-primary">{person.progress}%</strong></div><div className="progress-track h-1 rounded-full"><div className="progress-fill h-1 rounded-full" style={{width:`${person.progress}%`}}/></div></div>)}</div><Button asChild variant="secondary" size="sm" className="mt-4 w-full"><Link to="/project" hash="project-team">View team tasks</Link></Button></section>
      <section className="glass-panel rounded-[18px] p-4"><h2 className="text-sm font-bold">Needs Your Attention</h2><div className="mt-3 space-y-3"><div className="glass-inset rounded-xl p-3"><p className="text-xs font-semibold">Weekly report is pending</p><p className="mt-1 text-[11px] text-muted-foreground">Share your progress before Oct 09.</p></div><div className="glass-inset rounded-xl p-3"><p className="text-xs font-semibold">Supervisor feedback to review</p><p className="mt-1 text-[11px] text-muted-foreground">Check the latest note before your next test.</p></div></div><Button asChild variant="secondary" size="sm" className="mt-3 w-full"><Link to="/project">Review updates</Link></Button></section>
      <section className="glass-panel rounded-[18px] p-4"><h2 className="text-sm font-bold">Continue Building</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Pick up your Smart Car circuit. Review your next tasks and document your design progress.</p><div className="glass-inset mt-3 flex items-center gap-3 rounded-xl p-3"><CircuitBoard size={26} className="text-primary"/><div><p className="text-xs font-semibold">Your electronics workspace</p><p className="mt-1 text-[10px] text-muted-foreground">Plan · Build · Report</p></div></div><Button asChild variant="secondary" size="sm" className="mt-3 w-full"><Link to="/project"><Box size={14}/>View My Project</Link></Button></section>
      <section className="glass-panel rounded-[18px] p-4"><h2 className="text-sm font-bold">Learning Spotlight</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Before powering a circuit, check supply voltage, common ground, and motor driver connections.</p><div className="mt-3 flex flex-wrap gap-2"><span className="workshop-stock-badge">Power basics</span><span className="workshop-stock-badge">Sensor wiring</span></div><Button asChild variant="secondary" size="sm" className="mt-4 w-full"><Link to="/project">Review project goals</Link></Button></section>
    </div>
    <section className="glass-panel rounded-[18px] p-4 sm:p-5" aria-labelledby="workshop-stock-title">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-1 flex items-center gap-2"><Package size={19} className="text-primary" /><h2 id="workshop-stock-title" className="text-[17px] font-bold">Available in the Workshop</h2></div><p className="text-xs leading-5 text-muted-foreground">Find parts for your Smart Car and prepare a purchase request.</p></div><span className="workshop-demo-badge">Sample inventory</span></div>
      <div className="workshop-assistant-note mt-3 flex items-center gap-2 rounded-xl px-3 py-2 text-[11px]"><Wrench size={14} className="shrink-0" /><span>Workshop assistant updates will appear here. Stock and prices below are a preview.</span></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{inventory.map(item => {
        const request = requests.find(r => r.id === item.id), image = item.image;
        return <article key={item.id} className="glass-inset workshop-product flex min-w-0 flex-col rounded-2xl p-3.5"><div className="workshop-product-image relative mb-3 flex h-28 items-center justify-center rounded-xl">{image ? <img src={image} alt={item.name} className="h-24 w-full object-contain p-2" /> : <CircuitBoard size={42} className="text-primary" />}<span className="workshop-stock-badge absolute left-2 top-2">In stock</span></div><h3 className="text-xs font-bold leading-5">{item.name}</h3><p className="mt-1 text-[10px] text-muted-foreground">{item.location}</p><div className="mt-3 flex items-end justify-between"><p className="text-lg font-bold text-primary">${item.price}<span className="ml-1 text-[10px] font-normal text-muted-foreground">/ unit</span></p><span className="text-[11px] text-muted-foreground">{item.stock} available</span></div><div className="mt-3 border-t border-border/50 pt-3"><Button size="sm" variant={request ? "secondary" : "default"} className="w-full text-xs" onClick={() => {setSelected(item);setQuantity(request?.quantity ?? item.need);}}><ShoppingCart size={14}/>{request ? `Draft request · ${request.quantity}` : "Request to Buy"}</Button></div></article>;
      })}</div>
      {requests.length > 0 && <div role="status" className="workshop-assistant-note mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl p-3 text-xs"><span><CheckCircle2 size={14} className="mr-1 inline" />{requests.length} purchase drafts · ${pendingCost.toFixed(2)} estimated</span><span className="text-[10px]">Saved for this session · awaiting workshop integration</span></div>}
    </section>
    <Dialog open={selected!==null} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="glass-panel glass-strong"><DialogHeader><DialogTitle>Workshop Purchase Request</DialogTitle><DialogDescription>Prepare a local draft. No purchase or stock reservation is made.</DialogDescription></DialogHeader>{selected&&<form onSubmit={e=>{e.preventDefault();if(!Number.isInteger(quantity)||quantity<1||quantity>selected.stock)return;setRequests(current=>[...current.filter(r=>r.id!==selected.id),{id:selected.id,quantity}]);setSelected(null);}} className="space-y-4"><div className="glass-inset rounded-xl p-3"><p className="text-sm font-bold">{selected.name}</p><p className="mt-1 text-xs text-muted-foreground">${selected.price} per unit · {selected.stock} available</p></div><label className="block text-xs font-semibold" htmlFor="purchase-quantity">Quantity</label><input id="purchase-quantity" type="number" min={1} max={selected.stock} step={1} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="glass-inset h-10 w-full rounded-lg px-3 text-sm"/><div className="flex justify-between text-sm"><span>Estimated total</span><strong>${(selected.price*quantity).toFixed(2)}</strong></div><div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={()=>setSelected(null)}>Cancel</Button><Button type="submit" disabled={!Number.isInteger(quantity)||quantity<1||quantity>selected.stock}>Save Purchase Draft</Button></div></form>}</DialogContent></Dialog>
  </div>;
}